/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numberguess;

import java.util.Random;
import javax.swing.JOptionPane;


/**
 *
 * @author reli
 */
public class GuessGame extends javax.swing.JFrame {

    private int integerRand;
    private int count;
    
    /**
     * Creates new form GuessGame
     */
    public GuessGame() {
        initComponents();
        startNewGame();
    }
    
    public void startNewGame() {
        Random rand = new Random();
        integerRand = rand.nextInt(100) + 1;
        count = 0;
        JOptionPane.showMessageDialog(this, "You will start a number guessing game between 1 and 100. If you are ready go !");
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guessInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GuessGame");
        setPreferredSize(new java.awt.Dimension(350, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Enter the number to guess");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(58, 43, 211, 22);
        getContentPane().add(guessInput);
        guessInput.setBounds(58, 93, 211, 24);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 160, 94, 34);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Exit");
        jButton2.setPreferredSize(new java.awt.Dimension(76, 24));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(213, 154, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    JOptionPane.show
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int userInput = Integer.parseInt(guessInput.getText().trim());
            // Check if the input is out of bounds
            if (userInput < 1 || userInput > 100) {
                JOptionPane.showMessageDialog(this, "Please enter a number between 1 and 100.");
                return; // Exit the method without incrementing attempts
            }
             
            count++;
            
            if(userInput < integerRand) {
                JOptionPane.showMessageDialog(this, "Too small. Again !!");
            }
            else if(userInput > integerRand) {
                JOptionPane.showMessageDialog(this, "Too hight. Remove !!");
            }
            else {
                JOptionPane.showMessageDialog(this, "Congratulation !! You guess the number in " + count + " attempts");
                int playAgain = JOptionPane.showConfirmDialog(this, "Do you want to play again?", "Play Again", JOptionPane.YES_NO_OPTION);
                if(playAgain == JOptionPane.YES_OPTION) {
                    startNewGame();
                } else {
                    dispose();
                }   
            }
        } catch(Exception e) {
             // Handle invalid input (non-numeric values)
            JOptionPane.showMessageDialog(this, "Invalid input! Please enter a valid number between 1 and 100.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            JOptionPane.showMessageDialog(null, "Hello, World!", "Message", JOptionPane.INFORMATION_MESSAGE);

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
