/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scientificcalculator;

/**
 *
 * @author reli
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    private double num1;
    private double num2;
    private double resul;
    private String pro;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Screen = new javax.swing.JTextField();
        Digit00 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Power = new javax.swing.JButton();
        Sin = new javax.swing.JButton();
        Tang = new javax.swing.JButton();
        Multi = new javax.swing.JButton();
        Expo = new javax.swing.JButton();
        Modu = new javax.swing.JButton();
        log = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Digit08 = new javax.swing.JButton();
        Div = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Cos = new javax.swing.JButton();
        Digit07 = new javax.swing.JButton();
        Digit09 = new javax.swing.JButton();
        Sous = new javax.swing.JButton();
        Digit06 = new javax.swing.JButton();
        Digit05 = new javax.swing.JButton();
        Digit04 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Digit03 = new javax.swing.JButton();
        Digit02 = new javax.swing.JButton();
        Digit01 = new javax.swing.JButton();
        Comma = new javax.swing.JButton();
        Digit28 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Cubic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setPreferredSize(new java.awt.Dimension(450, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        Screen.setFont(new java.awt.Font("Linux Libertine Display O", 0, 24)); // NOI18N
        Screen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Screen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(Screen);
        Screen.setBounds(10, 10, 430, 45);

        Digit00.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit00.setText("0");
        Digit00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit00ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit00);
        Digit00.setBounds(10, 430, 72, 33);

        Exit.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(10, 70, 72, 33);

        Power.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Power.setText("x^y");
        getContentPane().add(Power);
        Power.setBounds(250, 130, 72, 33);

        Sin.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Sin.setText("sin");
        Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinActionPerformed(evt);
            }
        });
        getContentPane().add(Sin);
        Sin.setBounds(250, 190, 72, 33);

        Tang.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Tang.setText("tan");
        Tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TangActionPerformed(evt);
            }
        });
        getContentPane().add(Tang);
        Tang.setBounds(10, 190, 72, 33);

        Multi.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Multi.setText("*");
        Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiActionPerformed(evt);
            }
        });
        getContentPane().add(Multi);
        Multi.setBounds(370, 190, 70, 33);

        Expo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Expo.setText("e");
        Expo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpoActionPerformed(evt);
            }
        });
        getContentPane().add(Expo);
        Expo.setBounds(10, 130, 72, 33);

        Modu.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Modu.setText("%");
        Modu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuActionPerformed(evt);
            }
        });
        getContentPane().add(Modu);
        Modu.setBounds(370, 130, 70, 33);

        log.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        log.setText("ln");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log);
        log.setBounds(130, 130, 72, 33);

        Clear.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(370, 70, 70, 33);

        Digit08.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit08.setText("8");
        Digit08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit08ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit08);
        Digit08.setBounds(130, 250, 72, 33);

        Div.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Div.setText("/");
        Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivActionPerformed(evt);
            }
        });
        getContentPane().add(Div);
        Div.setBounds(370, 250, 70, 33);

        Remove.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Remove.setText("->");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(250, 70, 72, 33);

        Cos.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Cos.setText("cos");
        Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosActionPerformed(evt);
            }
        });
        getContentPane().add(Cos);
        Cos.setBounds(130, 190, 72, 33);

        Digit07.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit07.setText("7");
        Digit07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit07ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit07);
        Digit07.setBounds(10, 250, 72, 33);

        Digit09.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit09.setText("9");
        Digit09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit09ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit09);
        Digit09.setBounds(250, 250, 72, 33);

        Sous.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Sous.setText("-");
        Sous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SousActionPerformed(evt);
            }
        });
        getContentPane().add(Sous);
        Sous.setBounds(370, 310, 70, 33);

        Digit06.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit06.setText("6");
        Digit06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit06ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit06);
        Digit06.setBounds(250, 310, 72, 33);

        Digit05.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit05.setText("5");
        Digit05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit05ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit05);
        Digit05.setBounds(130, 310, 72, 33);

        Digit04.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit04.setText("4");
        Digit04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit04ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit04);
        Digit04.setBounds(10, 310, 72, 33);

        Add.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(370, 370, 70, 33);

        Digit03.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit03.setText("3");
        Digit03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit03ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit03);
        Digit03.setBounds(250, 370, 72, 33);

        Digit02.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit02.setText("2");
        Digit02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit02ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit02);
        Digit02.setBounds(130, 370, 72, 33);

        Digit01.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit01.setText("1");
        Digit01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit01ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit01);
        Digit01.setBounds(10, 370, 72, 33);

        Comma.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Comma.setText(".");
        Comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommaActionPerformed(evt);
            }
        });
        getContentPane().add(Comma);
        Comma.setBounds(130, 430, 72, 33);

        Digit28.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Digit28.setText("+/-");
        Digit28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit28ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit28);
        Digit28.setBounds(250, 430, 72, 33);

        Equal.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Equal.setText("=");
        Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualActionPerformed(evt);
            }
        });
        getContentPane().add(Equal);
        Equal.setBounds(370, 430, 70, 33);

        Cubic.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Cubic.setText("x^3");
        Cubic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CubicActionPerformed(evt);
            }
        });
        getContentPane().add(Cubic);
        Cubic.setBounds(130, 70, 72, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Digit03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit03ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "3");
    }//GEN-LAST:event_Digit03ActionPerformed

    private void Digit06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit06ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "6");
    }//GEN-LAST:event_Digit06ActionPerformed

    private void Digit07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit07ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "7");
    }//GEN-LAST:event_Digit07ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Digit00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit00ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "0");
    }//GEN-LAST:event_Digit00ActionPerformed

    private void Digit01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit01ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "1");
    }//GEN-LAST:event_Digit01ActionPerformed

    private void Digit02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit02ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "2");
    }//GEN-LAST:event_Digit02ActionPerformed

    private void Digit04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit04ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "4");
    }//GEN-LAST:event_Digit04ActionPerformed

    private void Digit05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit05ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "5");
    }//GEN-LAST:event_Digit05ActionPerformed

    private void Digit08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit08ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "8");
    }//GEN-LAST:event_Digit08ActionPerformed

    private void Digit09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit09ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + "9");
    }//GEN-LAST:event_Digit09ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        pro = "+";
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        String removeChart = null;
        
        if(Screen.getText().length() > 0) {
            StringBuilder Str = new StringBuilder(Screen.getText());
            Str.deleteCharAt(Screen.getText().length() - 1);
            removeChart = Str.toString();
            Screen.setText(removeChart);
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void SousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SousActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        pro = "-";
    }//GEN-LAST:event_SousActionPerformed

    private void DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        pro = "/";
    }//GEN-LAST:event_DivActionPerformed

    private void MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        pro = "*";
    }//GEN-LAST:event_MultiActionPerformed

    private void ModuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        pro = "%";
    }//GEN-LAST:event_ModuActionPerformed

    private void CubicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CubicActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Screen.getText());
        double res = num1 * num1 * num1;
        Screen.setText(Double.toString(res));
    }//GEN-LAST:event_CubicActionPerformed

    private void EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(Screen.getText());
        
        if(pro == "+"){
            resul = num1 + num2;
            Screen.setText(Double.toString(resul));
        }
        else if(pro == "-"){
            resul = num1 - num2;
            Screen.setText(Double.toString(resul));
        }
        else if(pro == "*"){
            resul = num1 * num2;
            Screen.setText(Double.toString(resul));
        }
        else if(pro == "/"){
            resul = num1 / num2;
            Screen.setText(Double.toString(resul));
        }
        else if(pro == "%"){
            resul = num1 % num2;
            Screen.setText(Double.toString(resul));
        }
    }//GEN-LAST:event_EqualActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Screen.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void TangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TangActionPerformed
        // TODO add your handling code here:
        double pr = Math.tan(Double.parseDouble(Screen.getText()));
        Screen.setText("");
        Screen.setText(Screen.getText() + pr);
    }//GEN-LAST:event_TangActionPerformed

    private void CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosActionPerformed
        // TODO add your handling code here:
        double pr = Math.cos(Double.parseDouble(Screen.getText()));
        Screen.setText("");
        Screen.setText(Screen.getText() + pr);
    }//GEN-LAST:event_CosActionPerformed

    private void SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinActionPerformed
        // TODO add your handling code here:
        double pr = Math.sin(Double.parseDouble(Screen.getText()));
        Screen.setText("");
        Screen.setText(Screen.getText() + pr);
    }//GEN-LAST:event_SinActionPerformed

    private void ExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpoActionPerformed
        // TODO add your handling code here:
        double pr = Math.exp(Double.parseDouble(Screen.getText()));
        Screen.setText("");
        Screen.setText(Screen.getText() + pr);
    }//GEN-LAST:event_ExpoActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        double pr = Math.log(Double.parseDouble(Screen.getText()));
        Screen.setText("");
        Screen.setText(Screen.getText() + pr);
    }//GEN-LAST:event_logActionPerformed

    private void CommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommaActionPerformed
        // TODO add your handling code here:
        Screen.setText(Screen.getText() + ".");
//        if(Screen.getText().length() < 0) {
//            Screen.setText("0.");
//        }
    }//GEN-LAST:event_CommaActionPerformed

    private void Digit28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit28ActionPerformed
        // TODO add your handling code here:
        Screen.setText(Double.toString(resul));
    }//GEN-LAST:event_Digit28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Comma;
    private javax.swing.JButton Cos;
    private javax.swing.JButton Cubic;
    private javax.swing.JButton Digit00;
    private javax.swing.JButton Digit01;
    private javax.swing.JButton Digit02;
    private javax.swing.JButton Digit03;
    private javax.swing.JButton Digit04;
    private javax.swing.JButton Digit05;
    private javax.swing.JButton Digit06;
    private javax.swing.JButton Digit07;
    private javax.swing.JButton Digit08;
    private javax.swing.JButton Digit09;
    private javax.swing.JButton Digit28;
    private javax.swing.JButton Div;
    private javax.swing.JButton Equal;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Expo;
    private javax.swing.JButton Modu;
    private javax.swing.JButton Multi;
    private javax.swing.JButton Power;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField Screen;
    private javax.swing.JButton Sin;
    private javax.swing.JButton Sous;
    private javax.swing.JButton Tang;
    private javax.swing.JButton log;
    // End of variables declaration//GEN-END:variables
}
